#! /bin/sh

### BEGIN INIT INFO
# Provides:		pcs
# Required-Start:	$local_fs $syslog
# Required-Stop:	$local_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	process control service
### END INIT INFO

set -e

# /etc/init.d/pcs: start and stop the process control service
SERVICE=/bin/pcs
PIDFILE=/var/run/pcs/pcs.pid

test -x $SERVICE || exit 0


if test -f /etc/default/pcs; then
    . /etc/default/pcs
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    PCS_OPTS="$PCS_OPTS $2"
fi

check_config() {
    $SERVICE $PCS_OPTS -t || exit 1
}

do_modprobe() {
    if [ -x /sbin/modprobe -a -f /proc/modules ]
    then
	modprobe -q "$1" || true
    fi
}


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting process control service" "pcs"
	do_modprobe lp8x4x_bus
	if start-stop-daemon --start --quiet --oknodo --nicelevel -20 --pidfile $PIDFILE --exec $SERVICE -- $PCS_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping process control service" "pcs"
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $SERVICE; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  restart|force-reload)
	check_config
	log_daemon_msg "Restarting process control service" "pcs"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE --exec $SERVICE
	if start-stop-daemon --start --quiet --oknodo --nicelevel -20 --pidfile $PIDFILE --exec $SERVICE -- $PCS_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  status)
	status_of_proc -p $PIDFILE $SERVICE pcs && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/pcs {start|stop|force-reload|restart|status}"
	exit 1
esac

exit 0
