#! /bin/sh

### BEGIN INIT INFO
# Provides:		pcs-net
# Required-Start:	$remote_fs $syslog $local_fs $network
# Required-Stop:	$remote_fs $syslog $local_fs $network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	process control service networking
### END INIT INFO

set -e

# /etc/init.d/pcs: start and stop the process control service
SERVICE=/bin/pcs-net
PIDFILE=/var/run/pcs/pcs-net.pid

test -x $SERVICE || exit 0


if test -f /etc/default/pcs; then
    . /etc/default/pcs
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    PCS_NET_OPTS="$PCS_NET_OPTS $2"
fi

check_config() {
    $SERVICE $PCS_NET_OPTS -t || exit 1
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting pcs networking" "pcs-net"
	if start-stop-daemon --start --quiet --oknodo --nicelevel 19 --pidfile $PIDFILE --exec $SERVICE -- $PCS_NET_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping pcs networking" "pcs-net"
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $SERVICE; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  restart)
	check_config
	log_daemon_msg "Restarting pcs networking" "pcs-net"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE --exec $SERVICE
	if start-stop-daemon --start --quiet --oknodo --nicelevel 19 --pidfile $PIDFILE --exec $SERVICE -- $PCS_NET_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  status)
	status_of_proc -p $PIDFILE $SERVICE pcs && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/pcs {start|stop|restart|status}"
	exit 1
esac

exit 0
